# Generated by Django 2.1.5 on 2019-02-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rate', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='advertise',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='homepage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='category',
            field=models.CharField(blank=True, choices=[('WEB_DEV', 'Web_Developer'), ('MOBILE_DEV', 'Mobile_Developer'), ('APP_DESIGN', 'Application_Design'), ('PROJECT_MANAGEMENT', 'Project_Management'), ('MARKETING', 'Marketing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.EmployerProfile'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='cv',
            field=models.FileField(blank=True, upload_to='files/cvs'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='login.Skill'),
        ),
        migrations.AddField(
            model_name='jobreq',
            name='advertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Advertise'),
        ),
        migrations.AddField(
            model_name='jobreq',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.JobSeekerProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.EmployerProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.JobSeekerProfile'),
        ),
    ]
