# Generated by Django 2.1.5 on 2019-02-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190205_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='skills',
            field=models.ManyToManyField(related_name='ad_skills', to='login.Skill'),
        ),
    ]
