# Generated by Django 2.1.5 on 2019-01-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_advertise_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='category',
            field=models.CharField(blank=True, choices=[('DEV', 'Developer')], max_length=3),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='cv',
            field=models.FileField(blank=True, upload_to='docs/cvs'),
        ),
    ]
